[package]
name = "karaoke-jobs"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
karaoke-domain = { workspace = true }
karaoke-infra = { workspace = true }
karaoke-events = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
tracing = { workspace = true }

[lib]
name = "karaoke_jobs"
path = "src/lib.rs"
